const mongoose=require('mongoose')
const bcrypt=require('bcryptjs');
const crudSchema=new mongoose.Schema(
    {
        email:{
            type:String
        },
        DOB:{
            type:String,
            required:true
        },
        mobile:{
            type:Number,
            required:true
        },
        firstName:{
            type:String,
            required:true
        },
        middleName:{
            type:String
        },
        lastName:{
            type:String,
            required:true
        },
        aadhar:{
            type:Number,
            required:true
        },
        password:{
            type:String,
            required:true
        },
        confirmPassword:{
            type:String
        },
        address:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        }
    }
)
module.exports = mongoose.model('crud', crudSchema);